# Generated by Django 3.1.1 on 2020-11-23 14:35

from django.db import migrations, models
import public.sqlite_listfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('friendly_name', models.CharField(blank=True, max_length=55, null=True)),
                ('province', models.CharField(max_length=10)),
                ('towns', public.sqlite_listfield.ListField()),
            ],
        ),
    ]
