# Generated by Django 3.1.1 on 2020-11-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=55, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='county',
            name='province',
            field=models.CharField(choices=[('ulster', 'Ulster'), ('leinster', 'Leinster'), ('munster', 'Munster'), ('connact', 'Connacht')], default='leinster', max_length=10, verbose_name='Province'),
        ),
    ]
