# Generated by Django 3.1.1 on 2020-11-24 12:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20201123_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=12, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='county',
            name='province',
            field=models.CharField(choices=[('ulster', 'Ulster'), ('leinster', 'Leinster'), ('munster', 'Munster'), ('connacht', 'Connacht')], default='leinster', max_length=10, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='county',
            name='towns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None),
        ),
    ]
