# Generated by Django 3.1.1 on 2020-11-24 18:40

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20201124_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'Counties'},
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=64, verbose_name='Band / Artist Name')),
                ('catalogue_name', django.contrib.postgres.fields.citext.CICharField(blank=True, max_length=72)),
                ('homecounty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.county')),
            ],
        ),
    ]
